name: xiaobei2
on:
  push:
    branches: [ stand ]
  # 这里是指定在UTC时间的0点运行, 也就是北京时间8点, 由于延迟并不是准点执行
  schedule:
    - cron: '0 0 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: use cache to speed up the time of build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: runTask
        env:
          # 必填
          YOUR_KEY: ${{ secrets.KEY_2 }}
        run: mvn compile exec:java -Dexec.mainClass="com.erzbir.xiaobei.Main"
