name: xiaobei2
on:
  push:
    branches: [ stand ]
  #schedule:
  #  - cron: '0 0 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: use cache to speed up the time of build
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: runTask
        env:
          YOUR_KEY: ${{ secrets.KEY }}
        run: mvn compile exec:java -Dexec.mainClass="com.erzbir.xiaobei.Main"
